import json

patch_data = {
 0: ("A Problem-Solving Agent is specifically designed to use search algorithms to find a sequence of actions that reach a goal state.", "وكيل حل المشكلات مصمم خصيصاً لاستخدام خوارزميات البحث للعثور على سلسلة من الإجراءات التي تصل إلى حالة الهدف."),
 1: ("Goal formulation is the first step because an agent must know its objective before it can formulate the problem to achieve it.", "صياغة الهدف هي الخطوة الأولى لأن الوكيل يجب أن يعرف هدفه قبل أن يتمكن من صياغة المشكلة لتحقيقه."),
 2: ("The basic problem-solving agent assumes the environment is discrete, not continuous.", "يفترض وكيل حل المشكلات الأساسي أن البيئة منفصلة وليست مستمرة."),
 3: ("The Transition Model formally defines what each action does by returning the resulting state.", "يحدد نموذج الانتقال رسمياً ما يفعله كل إجراء عن طريق إرجاع الحالة الناتجة."),
 4: ("The State Space is implicitly defined by the initial state, the possible actions, and the transition model.", "يتم تعريف مساحة الحالة ضمنياً من خلال الحالة الأولية، والإجراءات الممكنة، ونموذج الانتقال."),
 5: ("Abstraction helps simplify the problem by removing irrelevant details so the agent can focus on what matters.", "يساعد التجريد في تبسيط المشكلة عن طريق إزالة التفاصيل غير ذات الصلة ليتمكن الوكيل من التركيز على ما يهم."),
 6: ("It is an open-loop system because it executes its planned actions without checking its percepts again.", "إنه نظام حلقة مفتوحة لأنه ينفذ إجراءاته المخطط لها دون التحقق من مدركاته مرة أخرى."),
 7: ("The Path Cost function assigns a numeric cost to a path to help the agent find the optimal sequence.", "تقوم دالة تكلفة المسار بتعيين تكلفة رقمية للمسار لمساعدة الوكيل في العثور على التسلسل الأمثل."),
 8: ("An abstraction is valid if any abstract solution can be expanded into a real-world solution.", "يعتبر التجريد صالحاً إذا كان من الممكن توسيع أي حل مجرد إلى حل في العالم الحقيقي."),
 9: ("In non-deterministic environments, the agent needs a contingency plan to handle different possible outcomes.", "في البيئات غير الحتمية، يحتاج الوكيل إلى خطة طوارئ للتعامل مع النتائج المحتملة المختلفة."),
 10: ("Toy problems are used in AI because they can be given a concise, exact mathematical description for testing.", "تُستخدم المشاكل البسيطة (Toy problems) في الذكاء الاصطناعي لأنه يمكن إعطاؤها وصفاً رياضياً دقيقاً وموجزاً للاختبار."),
 11: ("The total number of world states is n (robot location) multiplied by 2^n (dirty/clean status of all locations).", "إجمالي عدد حالات العالم هو n (موقع الروبوت) مضروباً في 2^n (حالة النظافة لجميع المواقع)."),
 12: ("The 8-puzzle problem abstraction ignores the physical manipulation of the tiles and focuses only on their positions.", "يتجاهل تجريد مشكلة الـ 8-puzzle التلاعب المادي بالمربعات ويركز فقط على مواقعها."),
 13: ("It is superior because it drastically reduces the search space by only allowing legal non-attacking placements.", "إنه أفضل لأنه يقلل بشكل كبير من مساحة البحث من خلال السماح فقط بالوضعيات القانونية غير المهاجمة."),
 14: ("A touring problem requires the state to track all visited locations to ensure every location is visited exactly once.", "تتطلب مشكلة الجولة من الحالة تتبع جميع المواقع التي تمت زيارتها لضمان زيارة كل موقع مرة واحدة بالضبط."),
 15: ("GRAPH-SEARCH maintains an Explored Set to avoid getting stuck in loops or redundant paths.", "يحافظ GRAPH-SEARCH على مجموعة مستكشفة (Explored Set) لتجنب العالق في الحلقات أو المسارات المتكررة."),
 16: ("A node is a data structure used by the algorithm, whereas a state represents a physical configuration in the world.", "العقدة هي بنية بيانات تستخدمها الخوارزمية، بينما الحالة تمثل تكويناً مادياً في العالم."),
 17: ("Space Complexity is measured by the maximum number of nodes stored in memory during the search process.", "يُقاس تعقيد المساحة بأقصى عدد من العقد المخزنة في الذاكرة أثناء عملية البحث."),
 18: ("Iterative Deepening Search uses minimal memory (like DFS) but guarantees finding the shortest path (like BFS).", "يستخدم البحث بالتعميق التكراري ذاكرة قليلة (مثل DFS) ولكنه يضمن العثور على أقصر مسار (مثل BFS)."),
 19: ("Uniform-Cost Search is optimal only if all step costs are strictly positive, preventing infinite negative cost loops.", "يكون البحث بتكلفة موحدة مثالياً فقط إذا كانت جميع تكاليف الخطوات إيجابية بحتة، مما يمنع حلقات التكلفة السلبية اللانهائية."),
 20: ("DFS is heavily used because its linear space complexity makes it highly memory-efficient for deep problems.", "يُستخدم DFS بكثرة لأن تعقيد المساحة الخطي يجعله عالي الكفاءة في استخدام الذاكرة للمشاكل العميقة."),
 21: ("Bidirectional search requires exponential space because at least one of the search frontiers must be kept in memory.", "يتطلب البحث ثنائي الاتجاه مساحة أسية لأنه يجب الاحتفاظ بإحدى واجهات البحث في الذاكرة."),
 22: ("If a heuristic is admissible but not consistent, GRAPH-SEARCH might not find the optimal path without extra checks.", "إذا كان الاستدلال مقبولاً ولكنه غير متسق، فقد لا يجد GRAPH-SEARCH المسار الأمثل بدون فحوصات إضافية."),
 23: ("A consistent heuristic satisfies the triangle inequality: h(n) <= c(n,a,n') + h(n').", "الاستدلال المتسق يحقق متباينة المثلث: h(n) <= c(n,a,n') + h(n')."),
 24: ("RBFS often 'changes its mind' and forgets previously expanded nodes, leading to excessive recomputation (thrashing).", "غالباً ما يغير RBFS رأيه وينسى العقد الموسعة سابقاً، مما يؤدي إلى إعادة حساب مفرطة (Thrashing)."),
 25: ("A* is optimally efficient when the heuristic function used is consistent.", "تعتبر خوارزمية A* فعالة بشكل أمثل عندما تكون الدالة الاستدلالية المستخدمة متسقة."),
 26: ("Heuristic h2 dominates h1 if its estimated cost is always greater than or equal to h1's estimate for every node.", "يهيمن الاستدلال h2 على h1 إذا كانت تكلفته المقدرة أكبر من أو تساوي تقدير h1 لكل عقدة."),
 27: ("A branching factor close to 1 means the heuristic is highly accurate and guides the search directly to the goal.", "عامل التفرع القريب من 1 يعني أن الاستدلال دقيق للغاية ويوجه البحث مباشرة إلى الهدف."),
 28: ("A relaxed problem removes constraints, and its exact cost provides an optimistic, admissible heuristic for the real problem.", "المشكلة المخففة تزيل القيود، وتكلفتها الدقيقة توفر استدلالاً متفائلاً ومقبولاً للمشكلة الحقيقية."),
 29: ("To optimally combine non-dominating heuristics, take the maximum value of all heuristics at each node.", "للجمع بشكل أمثل بين الاستدلالات غير المهيمنة، خذ القيمة القصوى لجميع الاستدلالات في كل عقدة."),
 30: ("Machine Learning heuristics are statistical and might overestimate costs, breaking admissibility and losing optimality.", "الاستدلالات المبنية على التعلم الآلي إحصائية وقد تبالغ في التكلفة، مما يكسر المقبولية ويفقد المثالية."),
 31: ("A flat local maximum is a flat area in the state-space landscape from which no uphill exit exists.", "الحد الأقصى المحلي المسطح هو منطقة مسطحة في مشهد مساحة الحالة لا يوجد منها مخرج صاعد."),
 32: ("In simulated annealing, a worse move is accepted with probability e^(ΔE/T).", "في التلدين المحاكى، يتم قبول حركة أسوأ باحتمالية e^(ΔE/T)."),
 33: ("Stochastic Beam Search maintains diversity by choosing successors randomly with probabilities proportional to their values.", "يحافظ البحث الشعاعي العشوائي على التنوع عن طريق اختيار الخلفاء عشوائياً باحتمالات تتناسب مع قيمهم."),
 34: ("Crossover allows genetic algorithms to combine large blocks of useful features that evolved independently.", "يسمح التقاطع للخوارزميات الجينية بالجمع بين كتل كبيرة من الميزات المفيدة التي تطورت بشكل مستقل."),
 35: ("The Hessian matrix Hf(x) represents the matrix of second derivatives in continuous state spaces.", "تمثل مصفوفة هيسي Hf(x) مصفوفة المشتقات الثانية في مساحات الحالة المستمرة."),
 36: ("An AND-OR solution must cover all possible nondeterministic outcomes (AND nodes) while choosing one action (OR nodes).", "يجب أن يغطي حل AND-OR جميع النتائج المحتملة (عقد AND) مع اختيار إجراء واحد (عقد OR)."),
 37: ("A cyclic plan uses labels to handle failures by looping back to a previous state instead of giving up.", "تستخدم الخطة الدورية التسميات للتعامل مع الفشل عن طريق العودة إلى حالة سابقة بدلاً من الاستسلام."),
 38: ("For a problem with N states, the maximum number of possible belief states is 2^N (the power set).", "بالنسبة لمشكلة بها N من الحالات، فإن الحد الأقصى لعدد حالات الاعتقاد الممكنة هو 2^N."),
 39: ("The update stage filters the predicted belief state to only include states consistent with the actual percept.", "تقوم مرحلة التحديث بتصفية حالة الاعتقاد المتوقعة لتشمل فقط الحالات المتوافقة مع الإدراك الفعلي."),
 40: ("It is recursive because it computes the current belief state entirely from the immediately previous belief state and action.", "إنه عودي لأنه يحسب حالة الاعتقاد الحالية بالكامل من حالة الاعتقاد والإجراء السابقين مباشرة."),
 41: ("The competitive ratio compares the online agent's path cost to the optimal offline path cost.", "تقارن النسبة التنافسية تكلفة مسار الوكيل عبر الإنترنت بتكلفة المسار المثالي دون اتصال."),
 42: ("ONLINE-DFS requires reversible actions so it can backtrack when it hits a dead end.", "يتطلب ONLINE-DFS إجراءات قابلة للعكس حتى يتمكن من التراجع عندما يصل إلى طريق مسدود."),
 43: ("The state space must be safely explorable, guaranteeing that the goal is reachable from any reachable state.", "يجب أن تكون مساحة الحالة قابلة للاستكشاف بأمان، مما يضمن إمكانية الوصول إلى الهدف من أي حالة."),
 44: ("LRTA* escapes local minima by iteratively increasing the cost estimate of the current state until it finds a better path.", "يتجنب LRTA* الحدود الدنيا المحلية عن طريق زيادة تقدير تكلفة الحالة الحالية تكرارياً حتى يجد مساراً أفضل."),
 45: ("LRTA* assumes unknown actions are highly promising (optimism under uncertainty) to encourage exploration.", "يفترض LRTA* أن الإجراءات غير المعروفة واعدة للغاية (التفاؤل تحت عدم اليقين) لتشجيع الاستكشاف."),
 46: ("The agent learns the environment by building the transition table RESULT(s, a) from its experiences.", "يتعلم الوكيل البيئة من خلال بناء جدول الانتقال RESULT(s, a) من تجاربه."),
 47: ("Complex domains require general and flexible representations created through ontological engineering.", "تتطلب المجالات المعقدة تمثيلات عامة ومرنة يتم إنشاؤها من خلال الهندسة الأنطولوجية."),
 48: ("A general-purpose ontology must be flexible enough to unify and apply across any special-purpose domain.", "يجب أن تكون الأنطولوجيا ذات الأغراض العامة مرنة بما يكفي للتوحيد والتطبيق عبر أي مجال خاص."),
 49: ("CYC is the most prominent ontology construction system built entirely by trained logicians and ontologists.", "CYC هو أبرز نظام بناء أنطولوجيا تم بناؤه بالكامل بواسطة علماء منطق وعلماء وجود مدربين."),
 50: ("Reification is the process of turning a logical proposition into an individual object that can be reasoned about.", "التجسيد (Reification) هو عملية تحويل الاقتراح المنطقي إلى كائن فردي يمكن التفكير فيه."),
 51: ("If Dogs belong to DomesticatedSpecies, then DomesticatedSpecies is a category containing other categories.", "إذا كانت الكلاب تنتمي إلى الأنواع المستأنسة، فإن الأنواع المستأنسة هي فئة تحتوي على فئات أخرى."),
 52: ("A partition requires the subcategories to be both disjoint (no overlap) and exhaustive (covering the whole category).", "يتطلب التقسيم (Partition) أن تكون الفئات الفرعية منفصلة (لا تتداخل) وشاملة (تغطي الفئة بأكملها)."),
 53: ("The PartOf physical composition relation is strictly transitive and reflexive.", "علاقة التكوين المادي PartOf هي علاقة متعدية وانعكاسية بشكل صارم."),
 54: ("Physical properties like weight apply to physical objects, not to abstract mathematical sets.", "الخصائص الفيزيائية مثل الوزن تنطبق على الأشياء المادية، وليس على المجموعات الرياضية المجردة."),
 55: ("A substance category is characterized by intrinsic properties that remain true even if the substance is subdivided.", "تتميز فئة المادة (Substance) بخصائص جوهرية تظل صحيحة حتى لو تم تقسيم المادة."),
 56: ("Situation Calculus cannot model continuous or simultaneous actions, which is why Event Calculus was introduced.", "حساب الموقف (Situation Calculus) لا يمكنه نمذجة الإجراءات المستمرة أو المتزامنة، ولهذا تم إدخال حساب الحدث."),
 57: ("Clipped(f, (t1, t2)) means the fluent f was terminated by an event during the specified time interval.", "Clipped(f, (t1, t2)) يعني أن الخاصية f قد انتهت بسبب حدث خلال الفترة الزمنية المحددة."),
 58: ("A liquid event or process category means any subinterval of the process is also an instance of that process.", "حدث سائل أو فئة عملية يعني أن أي فترة فرعية من العملية هي أيضاً حالة من تلك العملية."),
 59: ("During(i, j) formally means interval i starts after j starts and ends before j ends.", "During(i, j) يعني رسمياً أن الفترة i تبدأ بعد بدء j وتنتهي قبل انتهاء j."),
 60: ("Logical terms in First-Order Logic are rigid designators; their identity cannot change dynamically over time.", "المصطلحات المنطقية في منطق الدرجة الأولى هي محددات جامدة؛ لا يمكن أن تتغير هويتها بمرور الوقت."),
 61: ("Referential Opacity prevents the substitution of equal terms in contexts involving propositional attitudes like belief.", "تمنع العتامة المرجعية استبدال المصطلحات المتساوية في السياقات التي تنطوي على مواقف مثل الاعتقاد."),
 62: ("Kripke semantics states that an agent knows P in world w if P is true in all worlds accessible from w.", "تنص دلالات كريبك على أن الوكيل يعرف P في العالم w إذا كان P صحيحاً في جميع العوالم التي يمكن الوصول إليها من w."),
 63: ("Inheritance algorithms search upwards and stop at the first value they find, automatically overriding distant defaults.", "تبحث خوارزميات الوراثة لأعلى وتتوقف عند أول قيمة تجدها، مما يتجاوز القيم الافتراضية البعيدة تلقائياً."),
 64: ("Description Logics are designed specifically to perform Subsumption and Classification tasks efficiently.", "تم تصميم منطق الوصف خصيصاً لأداء مهام التضمين والتصنيف بكفاءة."),
 65: ("The Nixon Diamond illustrates a conflict between inherited defaults, leaving the reasoner agnostic without a priority system.", "يوضح ماسة نيكسون صراعاً بين الافتراضات الموروثة، مما يترك المستدل غير قادر على اتخاذ قرار بدون نظام أولوية."),
 66: ("An ATMS tracks all valid assumptions simultaneously, making it vastly superior for switching between multiple contexts.", "يقوم ATMS بتتبع جميع الافتراضات الصالحة في وقت واحد، مما يجعله متفوقاً جداً في التبديل بين سياقات متعددة."),
 90: ("The actuators of an automated taxi are the physical controls it uses to act on the environment (steering, brakes).", "مشغلات سيارة الأجرة الآلية هي أدوات التحكم المادية التي تستخدمها للتأثير على البيئة (التوجيه، الفرامل)."),
 91: ("The environment is sequential because the diagnosis depends on the history of tests and progress over time.", "البيئة تسلسلية لأن التشخيص يعتمد على تاريخ الاختبارات والتقدم بمرور الوقت."),
 92: ("A Utility-based Agent is required because it can weigh conflicting goals (safety vs speed) to maximize overall happiness.", "هناك حاجة إلى وكيل قائم على المنفعة لأنه يمكنه الموازنة بين الأهداف المتضاربة (السلامة مقابل السرعة) لتعظيم المنفعة الإجمالية."),
 93: ("Adding randomization to its condition-action rules prevents the agent from getting stuck in deterministic infinite loops.", "إضافة العشوائية إلى قواعد الشرط والعمل يمنع الوكيل من العالق في حلقات حتمية لا نهائية."),
 94: ("A factored representation uses a fixed set of attributes (variables) to describe the state of the world.", "يستخدم التمثيل المفرز مجموعة ثابتة من السمات (المتغيرات) لوصف حالة العالم."),
 95: ("An omniscient agent magically knows the actual outcome, whereas a rational agent acts optimally based on its available percepts.", "يعرف الوكيل العليم النتيجة الفعلية بطريقة سحرية، بينما يتصرف الوكيل العقلاني على النحو الأمثل بناءً على مدركاته."),
 96: ("If an agent cannot adjust its behavior based on its own experience and percepts, it completely lacks autonomy.", "إذا لم يتمكن الوكيل من تعديل سلوكه بناءً على خبرته ومدركاته، فإنه يفتقر تماماً إلى الاستقلالية."),
 97: ("Chess with a clock is semidynamic because the environment doesn't change, but the agent's performance score decreases over time.", "لعبة الشطرنج مع ساعة تعتبر شبه ديناميكية لأن البيئة لا تتغير، لكن درجة أداء الوكيل تتناقص بمرور الوقت."),
 98: ("Without knowing its location, the reflex agent cannot distinguish states that require different actions, causing infinite loops.", "بدون معرفة موقعه، لا يستطيع الوكيل المنعكس التمييز بين الحالات التي تتطلب إجراءات مختلفة، مما يتسبب في حلقات لا نهائية."),
 99: ("A model-based agent requires knowledge of how the world evolves independently and what its own actions do to update its state.", "يتطلب الوكيل القائم على النموذج معرفة كيف يتطور العالم بشكل مستقل وما تفعله أفعاله لتحديث حالته."),
 100: ("The Critic evaluates the agent's performance against a fixed standard and provides feedback to the learning element.", "يقوم الناقد (Critic) بتقييم أداء الوكيل مقابل معيار ثابت ويقدم ملاحظات لعنصر التعلم."),
 101: ("An entity is an 'agent' if it acts to maximize a performance measure based on its interactions with the environment.", "يعتبر الكيان 'وكيلاً' إذا كان يتصرف لزيادة مقياس الأداء بناءً على تفاعلاته مع البيئة."),
 102: ("Goal-based agents represent goals explicitly, making them flexible enough to adapt to changes without rewriting all rules.", "يمثل الوكلاء القائمون على الهدف الأهداف بشكل صريح، مما يجعلهم مرنين بدرجة كافية للتكيف مع التغييرات دون إعادة كتابة كل القواعد."),
 103: ("A structured representation is necessary to model specific objects and the explicit logical relationships between them.", "التمثيل المنظم ضروري لنمذجة كائنات محددة والعلاقات المنطقية الصريحة بينها."),
 104: ("An Environment Generator allows testing the agent's robustness and average performance across a variety of unpredictable conditions.", "يسمح مُولِّد البيئة باختبار متانة الوكيل وأدائه المتوسط عبر مجموعة متنوعة من الظروف غير المتوقعة.")
}

with open('D:/MasterMCQ/Artificial Intelligence/Artificial Intelligence_cache.json', 'r', encoding='utf-8') as f:
    cache = json.load(f)

for idx, (exp_en, exp_ar) in patch_data.items():
    cache[idx]['explanation']['en'] = exp_en
    cache[idx]['explanation']['ar'] = exp_ar

with open('D:/MasterMCQ/Artificial Intelligence/Artificial Intelligence_cache.json', 'w', encoding='utf-8') as f:
    json.dump(cache, f, ensure_ascii=False, indent=2)

print("Applied real AI explanations successfully!")
